export const allowedTabsByRole: Record<string, string[]> = {
  EMPLOYEE: ["my-report", "balances", "reference", "apply"],
  AUDITOR: ["audit-records", "audit-trail", "audit-adjustments", "audit-compliance", "audit-reports", "my-report", "balances", "reference", "apply"],
  BOARD: ["my-report", "balances", "reference", "apply"],
  DEPARTMENT_MANAGER: ["dm-pending", "dm-approved", "dm-rejected", "calendar", "my-report", "balances", "reference", "apply"],
  HR_STAFF: ["staff-all", "staff-pending", "staff-approved", "staff-forwarded", "calendar", "my-report", "balances", "reference", "apply"],
  HR_MANAGER: [
    "hm-high",
    "manager-approvals",
    "manager-process-hr-admin",
    "hm-escalated",
    "hm-all",
    "hm-overview",
    "hm-overrides",
    "calendar",
    "my-report",
    "balances",
    "reference",
    "apply",
  ],
  HR_ADMIN: ["hr-final", "hr-records", "hr-balances", "hr-types", "hr-policies", "calendar", "my-report", "balances", "reference", "apply"],
  EXECUTIVE: [
    "exec-summary",
    "exec-approvals",
    "exec-trends",
    "exec-availability",
    "exec-reports",
    "my-report",
    "balances",
    "reference",
    "apply",
  ],
  SUPER_ADMIN: ["admin-process", "admin-process-hr-manager", "admin-record-executive", "company-report", "employee-balances", "my-report", "balances", "reference", "apply"],
  DEFAULT: ["my-report", "balances", "reference", "apply"],
};

export const defaultTabByRole: Record<string, string> = {
  EMPLOYEE: "my-report",
  AUDITOR: "audit-records",
  BOARD: "my-report",
  DEPARTMENT_MANAGER: "dm-pending",
  HR_STAFF: "staff-all",
  HR_MANAGER: "hm-high",
  HR_ADMIN: "hr-final",
  EXECUTIVE: "exec-summary",
  SUPER_ADMIN: "admin-process",
  DEFAULT: "my-report",
};
