import ComplaintManagerEscalatedPageComponent from "@/features/complaints/components/ComplaintManagerEscalatedPage";

export const ComplaintManagerEscalatedPage = ComplaintManagerEscalatedPageComponent;
